export const NAVIGATE_TO_LIST = 'NAVIGATE TO LIST';

export const DATA_HAS_ERRORED = 'DATA HAS ERRORED';
export const DATA_IS_LOADING = 'DATA IS LOADING';
export const FETCH_DATA_SUCCESS = 'FETCH DATA SUCCESS';
